DATASET_IMAGES_FOLDER = "./dataset"
TEST_IMAGES_FOLDER = "./test_images"
TESTED_IMAGES_FOLDER = "./tested_images"
RESULT_IMAGES_FOLDER = "./result_images"
DETECT_MODEL = "cnn"
PICKLE_PATH = "./encodings.pickle"
FIREBASE_SERVICE_ACCOUN_PATH = "./*.json"